# Generated by Django 2.2.6 on 2019-10-21 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushapplication',
            name='api_key',
            field=models.CharField(max_length=255),
        ),
    ]
