# Generated by Django 2.2.6 on 2019-10-23 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('push_app', '0002_auto_20191021_0347'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('push_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='push_app.PushApplication')),
            ],
        ),
        migrations.CreateModel(
            name='MessageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('token', models.CharField(default=None, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('push_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_datas', to='push_app.PushApplication')),
            ],
        ),
    ]
